/*
Copyright (c) 2014-2026 AscEmu Team <http://www.ascemu.org>
This file is released under the MIT license. See README-MIT for more information.
*/

#pragma once

#include <cstdint>

namespace AscEmu::Version::Forever
{
    enum class Opcode : uint16_t
    {
        NONE = 0,

        CMSG_PING,
        CMSG_ENUM_CHARACTERS,
        CMSG_CHECK_CHARACTER_NAME_AVAILABILITY,
        CMSG_CREATE_CHARACTER,
        CMSG_PLAYER_LOGIN,
        CMSG_CHAR_DELETE,
        CMSG_DB_QUERY_BULK,
        CMSG_HOTFIX_REQUEST,
        CMSG_QUERY_CREATURE,
        CMSG_GET_UNDELETE_CHARACTER_COOLDOWN_STATUS,
        CMSG_BATTLE_PAY_GET_PURCHASE_LIST,
        CMSG_BATTLE_PAY_GET_PRODUCT_LIST,
        CMSG_UPDATE_VAS_PURCHASE_STATES,
        CMSG_QUICK_JOIN_AUTO_ACCEPT_REQUESTS,
        CMSG_GET_LAST_CATALOG_FETCH,
        CMSG_SOCIAL_CONTRACT_REQUEST,
        CMSG_SOCIAL_CONTRACT_ACCEPT,
        CMSG_SERVER_TIME_OFFSET_REQUEST,
        CMSG_CHARACTER_SELECT_GATE_ACK,
        CMSG_CHARACTER_LIST_ACK,
        CMSG_UPDATE_ACCOUNT_DATA,

        SMSG_PONG,
        SMSG_ENUM_CHARACTERS_RESULT,
        SMSG_CHARACTER_LIST_STATE,
        SMSG_CHECK_CHARACTER_NAME_AVAILABILITY_RESULT,
        SMSG_CREATE_CHAR,
        SMSG_DELETE_CHAR,
        SMSG_DB_REPLY,
        SMSG_AVAILABLE_HOTFIXES,
        SMSG_CACHE_VERSION,
        SMSG_QUERY_CREATURE_RESPONSE,
        SMSG_UNDELETE_COOLDOWN_STATUS_RESPONSE,
        SMSG_SOCIAL_CONTRACT_REQUEST_RESPONSE,
        SMSG_SERVER_TIME_OFFSET,
        SMSG_ACCOUNT_ITEM_COLLECTION_DATA,
        SMSG_ACCOUNT_DATA_TIMES,
        SMSG_FEATURE_SYSTEM_STATUS,
        SMSG_SET_TIME_ZONE_INFORMATION,
        SMSG_LOGIN_VERIFY_WORLD,
        SMSG_LOGIN_SET_TIME_SPEED,
        SMSG_UPDATE_OBJECT,
        SMSG_UPDATE_ACCOUNT_DATA_COMPLETE,
        SMSG_CHARACTER_ENUM_PRELUDE,
        SMSG_CHARACTER_ENUM_PRELUDE_EXTENDED,
        SMSG_CHARACTER_SELECT_STATUS,
        SMSG_CHARACTER_SELECT_GATE
    };
}
