/*
Copyright (c) 2014-2025 AscEmu Team <http://www.ascemu.org>
This file is released under the MIT license. See README-MIT for more information.
*/

#pragma once

#include "CommonTypes.hpp"
#include "Database.hpp"

enum WorldDatabaseStatements : uint32_t
{
    // Update
    WORLD_VERSION_LAST_UPDATE,

    // Server
    WORLD_SEL_TABLE_EXISTS,
    WORLD_SEL_CREATURE_MOVEMENT_PROPS,
    WORLD_SEL_GAMEOBJECT_QUEST_ITEM_BINDING,

    // Auctions
    WORLD_AUCTIONHOUSE_GROUPS_SELECT,
    WORLD_AUCTIONHOUSE_ENTRIES_SELECT,

    // Achievements
    WORLD_ACHIEVEMENT_REWARD_SELECT_ALL,

    // Quests
    WORLD_QUEST_ITEM_BINDING_BY_QUEST,
    WORLD_CREATURE_QUEST_STARTER_BY_QUEST,
    WORLD_CREATURE_SPAWN_BY_ENTRY,
    WORLD_GO_QUEST_STARTER_BY_QUEST,
    WORLD_GO_SPAWN_BY_ENTRY,
    WORLD_QUEST_LIST_BY_CREATURE,
    WORLD_CREATURE_QUEST_STARTER_EXISTS,
    WORLD_CREATURE_QUEST_STARTER_INSERT,
    WORLD_CREATURE_QUEST_FINISHER_EXISTS,
    WORLD_CREATURE_QUEST_FINISHER_INSERT,
    WORLD_CREATURE_QUEST_STARTER_SELECT,
    WORLD_CREATURE_QUEST_STARTER_DELETE,
    WORLD_CREATURE_QUEST_FINISHER_SELECT,
    WORLD_CREATURE_QUEST_FINISHER_DELETE,
    WORLD_QUEST_FINISHER_CREATURE_SELECT,
    WORLD_QUEST_FINISHER_CREATURE_SPAWNID_SELECT,
    WORLD_QUEST_FINISHER_OBJECT_SELECT,
    WORLD_QUEST_FINISHER_OBJECT_SPAWNID_SELECT,
    WORLD_QUEST_STARTER_CREATURE_SELECT,
    WORLD_QUEST_STARTER_CREATURE_SPAWN_LOCATION_SELECT,
    WORLD_QUEST_FINISHER_CREATURE_SPAWN_LOCATION_SELECT,
    WORLD_ITEM_QUEST_ASSOCIATION_SELECT,
    WORLD_QUEST_POI_SELECT,
    WORLD_QUEST_POI_POINTS_SELECT,


    // Creatures
    WORLD_CREATURE_ENTRIES_BY_MAP,
    WORLD_CREATURE_SPAWN_WAYPOINT_UPDATE,
    WORLD_CREATURE_CANFLY_UPDATE,
    WORLD_CREATURE_EMOTE_STATE_UPDATE,
    WORLD_CREATURE_FLAGS_UPDATE,
    WORLD_CREATURE_SPAWN_PHASE_UPDATE,
    WORLD_CREATURE_SPAWN_STANDSTATE_UPDATE,
    WORLD_CREATURE_MOVEMENT_OVERRIDE_SELECT_ALL,
    WORLD_CREATURE_SPAWN_EXISTS_BY_ID,
    WORLD_CREATURE_TIMED_EMOTES_SELECT_ALL,
    WORLD_CREATURE_SELECT_WAYPOINTS,
    WORLD_CREATURE_INSERT_WAYPOINT,
    WORLD_CREATURE_DELETE_WAYPOINT,
    WORLD_CREATURE_DELETE_ALL_WAYPOINTS_BY_ID,
    WORLD_SEL_MAX_ITEMPAGE_ENTRY,
    WORLD_SEL_CREATURE_FORMATIONS,
    WORLD_SEL_CREATURE_SPAWN_BY_ID,
    WORLD_DEL_CREATURE_SPAWN_BY_ID_AND_BUILD,
    WORLD_INS_CREATURE_SPAWN,
    WORLD_DEL_CREATURE_SPAWN_VERSIONED,
    WORLD_SEL_CREATURE_DIFFICULTY,
    WORLD_SEL_DISPLAY_BOUNDING_BOXES,
    WORLD_SEL_VENDOR_RESTRICTIONS,
    WORLD_SEL_NPC_GOSSIP_TEXTS,
    WORLD_SEL_NPC_SCRIPT_TEXT,
    WORLD_SEL_GOSSIP_MENU_OPTION,
    WORLD_SEL_GRAVEYARDS,
    WORLD_SEL_SPELL_TELEPORT_COORDS,
    WORLD_SEL_FISHING,
    WORLD_SEL_WORLDMAP_INFO,
    WORLD_SEL_ZONE_GUARDS,
    WORLD_SEL_BATTLEMASTERS,
    WORLD_SEL_TOTEMDISPLAYIDS,
    WORLD_SEL_SPELLCLICKSPELLS,
    WORLD_SEL_WORLDSTRING_TABLES,
    WORLD_SEL_POINTS_OF_INTEREST,
    WORLD_SEL_LINKED_SET_BONUS,
    WORLD_SEL_INITIAL_EQUIPMENT,
    WORLD_SEL_PLAYER_CREATE_INFO,
    WORLD_SEL_PLAYER_CREATE_INFO_BARS,
    WORLD_SEL_PLAYER_CREATE_INFO_ITEMS,
    WORLD_SEL_PLAYER_CREATE_INFO_SKILLS,
    WORLD_SEL_PLAYER_CREATE_INFO_SPELLS,
    WORLD_SEL_PLAYER_CREATE_INFO_SPELLS_CAST,
    WORLD_SEL_PLAYER_LEVELSTATS,
    WORLD_SEL_PLAYER_CLASSLEVELSTATS,
    WORLD_SEL_PLAYER_XP_TO_LEVEL,
    WORLD_SEL_SPELLOVERRIDE,
    WORLD_SEL_SPELLID_FOR_OVERRIDEID,
    WORLD_SEL_NPC_GOSSIP_PROPERTIES,
    WORLD_SEL_PET_LEVEL_ABILITIES,
    WORLD_SEL_AREA_TRIGGER,
    WORLD_SEL_FILTER_CHARACTER_NAMES,
    WORLD_SEL_FILTER_CHAT,
    WORLD_SEL_LOCALES_CREATURE,
    WORLD_SEL_LOCALES_GAMEOBJECT,
    WORLD_SEL_LOCALES_GOSSIP_MENU_OPTION,
    WORLD_SEL_LOCALES_ITEM,
    WORLD_SEL_LOCALES_ITEM_PAGES,
    WORLD_SEL_LOCALES_NPC_SCRIPT_TEXT,
    WORLD_SEL_LOCALES_NPC_GOSSIP_TEXTS,
    WORLD_SEL_LOCALES_QUEST,
    WORLD_SEL_LOCALES_WORLDBROADCAST,
    WORLD_SEL_LOCALES_WORLDMAP_INFO,
    WORLD_SEL_LOCALES_WORLDSTRING_TABLE,
    WORLD_SEL_PROFESSION_DISCOVERIES,
    WORLD_SEL_TRANSPORT_DATA,
    WORLD_SEL_GAMEOBJECT_PROPERTIES_TYPE_15,
    WORLD_SEL_GO_PROPERTIES_TYPE_15_PARAM6,
    WORLD_SEL_GOSSIP_MENU,
    WORLD_SEL_GOSSIP_MENU_ITEMS,
    WORLD_SEL_CREATURE_AI_SCRIPTS,
    WORLD_SEL_SPAWN_GROUP_ID,
    WORLD_SEL_CREATURE_GROUP_SPAWN,
    WORLD_SEL_SCRIPT_SPLINE_CHAIN_META,
    WORLD_SEL_SCRIPT_SPLINE_CHAIN_WAYPOINTS,
    WORLD_SEL_ITEM_PROPERTIES,
    WORLD_SEL_ITEM_PAGES,
    WORLD_SEL_CREATURE_PROPERTIES,
    WORLD_SEL_GAMEOBJECT_PROPERTIES,
    WORLD_SEL_GAMEOBJECT_SPAWNS_EXTRA,
    WORLD_SEL_GAMEOBJECT_SPAWNS_OVERRIDES,
    WORLD_SEL_QUEST_PROPERTIES,
    WORLD_SEL_WORLDBROADCAST,
    WORLD_SEL_CREATURE_SPAWNS_BASE,
    WORLD_SEL_GAMEOBJECT_SPAWNS_BASE,
    WORLD_SEL_RECALL,
    WORLD_SEL_CREATURE_QUEST_STARTER,
    WORLD_SEL_GAMEOBJECT_QUEST_STARTER,
    WORLD_SEL_ALL_CREATURE_QUEST_STARTER,
    WORLD_SEL_ALL_CREATURE_QUEST_FINISHER,
    WORLD_SEL_ALL_GAMEOBJECT_QUEST_STARTER,
    WORLD_SEL_ALL_GAMEOBJECT_QUEST_FINISHER,
    WORLD_SEL_VENDORS,
    WORLD_SEL_TRAINER_PROPERTIES_SPELLSET,
    WORLD_SEL_TRAINER_PROPERTIES,
    WORLD_SEL_MAX_CREATURE_SPAWN_ID,
    WORLD_SEL_MAX_GAMEOBJECT_SPAWN_ID,
    WORLD_SEL_CREATURE_WAYPOINTS,
    WORLD_SEL_MAX_CREATURE_WAYPOINT_ID,
    WORLD_SEL_LOOT_CREATURES,
    WORLD_SEL_LOOT_GAMEOBJECTS,
    WORLD_SEL_LOOT_SKINNING,
    WORLD_SEL_LOOT_FISHING,
    WORLD_SEL_LOOT_ITEMS,
    WORLD_SEL_LOOT_PICKPOCKETING,


    // Loot
    WORLD_LOOT_CREATURES_BY_ENTRY,

    // Reputation
    WORLD_REPUTATION_CREATURE_ONKILL_SELECT,
    WORLD_REPUTATION_FACTION_ONKILL_SELECT,
    WORLD_REPUTATION_INSTANCE_ONKILL_SELECT,

    // Vendor
    WORLD_VENDOR_INSERT,
    WORLD_VENDOR_DELETE,

    // Recall
    WORLD_RECALL_INSERT,
    WORLD_RECALL_DELETE_BY_NAME,

    // Gameobjects
    WORLD_GAMEOBJECT_POSITION_UPDATE,
    WORLD_GAMEOBJECT_SPAWN_OVERRIDE_REPLACE,
    WORLD_GAMEOBJECT_SPAWN_PHASE_UPDATE,
    WORLD_GAMEOBJECT_SPAWN_STATE_UPDATE,
    WORLD_INS_GAMEOBJECT_SPAWN,
    WORLD_UPD_GAMEOBJECT_SPAWN,
    WORLD_DEL_GAMEOBJECT_SPAWN,
    WORLD_DEL_GAMEOBJECT_SPAWN_EXTRA,
    WORLD_DEL_GAMEOBJECT_SPAWN_OVERRIDES,
    WORLD_SEL_GAMEOBJECT_QUEST_PICKUP_BINDING,
    WORLD_SEL_GAMEOBJECT_TELEPORTS,

    // Vehicles
    WORLD_VEHICLE_ACCESSORY_SELECT_ALL,
    WORLD_VEHICLE_SEAT_ADDON_SELECT_ALL,

    // Items
    WORLD_ITEM_RANDOMPROP_GROUPS_SELECT,
    WORLD_ITEM_RANDOMSUFFIX_GROUPS_SELECT,

    // Gameevents
    WORLD_GAMEEVENT_PROPERTIES_SELECT,
    WORLD_EVENT_CREATURE_SPAWNS_SELECT,
    WORLD_EVENT_GAMEOBJECT_SPAWNS_SELECT,

    // Guild
    WORLD_GUILD_XP_FOR_LEVEL_SELECT,
    WORLD_GUILD_REWARDS_SELECT,

    // Taxi
    WORLD_SELECT_TAXI_LEVEL_DATA,

    // Weather
    WORLD_SELECT_WEATHER_DATA,

    // Script
    WORLD_EVENT_SCRIPTS_SELECT_ALL,

    // Instance
    WORLD_INSTANCE_ENCOUNTERS_SELECT_ALL,

    // LFG
    WORLD_SEL_LFG_DUNGEON_REWARDS,


    // Worldstate
    WORLD_WORLDSTATE_TEMPLATES_SELECT_MAPS,
    WORLD_WORLDSTATE_TEMPLATES_SELECT_ALL,

    // Spell
    WORLD_SEL_SPELL_COEFF_OVERRIDE,
    WORLD_SEL_SPELL_CUSTOM_OVERRIDE,
    WORLD_SEL_AI_THREAT_TO_SPELLID,
    WORLD_SEL_SPELL_EFFECTS_OVERRIDE,
    WORLD_SEL_SPELL_AREA,
    WORLD_SEL_SPELL_REQUIRED,
    WORLD_SEL_SPELL_TARGET_CONSTRAINTS,
    WORLD_SEL_SPELL_RANKS,
    WORLD_SEL_SPELL_DISABLE,

    // LUA LOOT
    WORLD_SEL_LOOT_ITEM_ENTRY_ITEM,
    WORLD_REP_LOOT_ITEM,
    WORLD_SEL_LOOT_GAMEOBJECT_ENTRY_ITEM,
    WORLD_REP_LOOT_GAMEOBJECT,
    WORLD_SEL_LOOT_CREATURE_ENTRY_ITEM,
    WORLD_REP_LOOT_CREATURE,

    MAX_WORLDDATABASE_STATEMENTS
};

class SERVER_DECL WorldDatabaseConnection : public Database
{
public:
    typedef WorldDatabaseStatements Statements;

    WorldDatabaseConnection();
    ~WorldDatabaseConnection();

    void PrepareStatements() override;
};
